"""HTML report generator — creates readable reports from diff or run data.

Generates self-contained HTML reports with embedded CSS styling.
Designed to be readable by non-technical audience.
"""

import os
from datetime import datetime, timezone
from typing import Any, Dict, Optional

from homeshield.utils.logging_config import get_logger
from homeshield.utils.output import ensure_directory

logger = get_logger("report.html_report")


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HomeShield Report — {title}</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 960px;
            margin: 0 auto;
            padding: 24px;
            background: #f5f7fa;
        }}
        .header {{
            background: linear-gradient(135deg, #1a5276, #2e86c1);
            color: white;
            padding: 32px;
            border-radius: 12px;
            margin-bottom: 24px;
        }}
        .header h1 {{ font-size: 28px; margin-bottom: 8px; }}
        .header .subtitle {{ opacity: 0.85; font-size: 14px; }}
        .score-card {{
            display: flex;
            gap: 20px;
            margin-bottom: 24px;
        }}
        .score-box {{
            flex: 1;
            background: white;
            border-radius: 12px;
            padding: 24px;
            text-align: center;
            box-shadow: 0 2px 8px rgba(0,0,0,0.08);
        }}
        .score-box .label {{ font-size: 14px; color: #666; margin-bottom: 8px; }}
        .score-box .value {{ font-size: 48px; font-weight: 700; }}
        .score-box.before .value {{ color: #e74c3c; }}
        .score-box.after .value {{ color: #27ae60; }}
        .score-box.change .value {{ color: #2e86c1; }}
        .verdict {{
            padding: 16px 24px;
            border-radius: 8px;
            margin-bottom: 24px;
            font-size: 16px;
            font-weight: 500;
        }}
        .verdict.improved {{ background: #d5f5e3; color: #1e8449; border-left: 4px solid #27ae60; }}
        .verdict.unchanged {{ background: #fdebd0; color: #b9770e; border-left: 4px solid #f39c12; }}
        .verdict.degraded {{ background: #fadbd8; color: #c0392b; border-left: 4px solid #e74c3c; }}
        .section {{
            background: white;
            border-radius: 12px;
            padding: 24px;
            margin-bottom: 24px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.08);
        }}
        .section h2 {{
            font-size: 20px;
            margin-bottom: 16px;
            padding-bottom: 8px;
            border-bottom: 2px solid #eee;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin-top: 12px;
        }}
        th {{
            background: #f8f9fa;
            text-align: left;
            padding: 10px 12px;
            font-weight: 600;
            font-size: 13px;
            text-transform: uppercase;
            color: #666;
            border-bottom: 2px solid #dee2e6;
        }}
        td {{
            padding: 10px 12px;
            border-bottom: 1px solid #eee;
            font-size: 14px;
        }}
        tr:hover td {{ background: #f8f9fa; }}
        .tag {{
            display: inline-block;
            padding: 2px 8px;
            border-radius: 4px;
            font-size: 12px;
            font-weight: 600;
        }}
        .tag.added {{ background: #fadbd8; color: #c0392b; }}
        .tag.removed {{ background: #d5f5e3; color: #1e8449; }}
        .tag.open {{ background: #fadbd8; color: #c0392b; }}
        .tag.closed {{ background: #d5f5e3; color: #1e8449; }}
        .tag.timeout {{ background: #fdebd0; color: #b9770e; }}
        .empty {{ color: #999; font-style: italic; padding: 16px 0; }}
        .footer {{
            text-align: center;
            color: #999;
            font-size: 12px;
            margin-top: 32px;
            padding-top: 16px;
            border-top: 1px solid #ddd;
        }}
    </style>
</head>
<body>
    {content}
    <div class="footer">
        Generated by HomeShield v1.0.0 on {generated_at}
    </div>
</body>
</html>"""


def generate_diff_report(diff_data: Dict[str, Any], output_path: str) -> str:
    """Generate an HTML report from diff data.

    Args:
        diff_data: Parsed diff.json structure.
        output_path: Path for the output HTML file.

    Returns:
        Absolute path of the generated HTML file.
    """
    logger.info("Generating diff HTML report: %s", output_path)

    try:
        title = f"{diff_data.get('before_label', 'Before')} vs {diff_data.get('after_label', 'After')}"
        scores = diff_data.get("scores", {})
        summary = diff_data.get("summary", {})
        disc_delta = diff_data.get("discovery_delta", {})
        reach_delta = diff_data.get("reachability_delta", {})

        # Build content sections
        content_parts = []

        # Header
        content_parts.append(f"""
    <div class="header">
        <h1>HomeShield Exposure Report</h1>
        <div class="subtitle">Comparing: {diff_data.get('before_label', 'N/A')} → {diff_data.get('after_label', 'N/A')}</div>
        <div class="subtitle">Generated: {diff_data.get('timestamp_utc', 'N/A')}</div>
    </div>""")

        # Score cards
        before_score = scores.get("before", "N/A")
        after_score = scores.get("after", "N/A")
        improvement = scores.get("improvement", 0)
        change_sign = "+" if improvement > 0 else ""

        content_parts.append(f"""
    <div class="score-card">
        <div class="score-box before">
            <div class="label">Before (Baseline)</div>
            <div class="value">{before_score}</div>
        </div>
        <div class="score-box after">
            <div class="label">After (Hardened)</div>
            <div class="value">{after_score}</div>
        </div>
        <div class="score-box change">
            <div class="label">Change</div>
            <div class="value">{change_sign}{improvement}</div>
        </div>
    </div>""")

        # Verdict
        verdict = summary.get("verdict", "UNCHANGED").lower()
        description = summary.get("description", "No summary available.")
        content_parts.append(f"""
    <div class="verdict {verdict}">
        <strong>{verdict.upper()}:</strong> {description}
    </div>""")

        # Discovery delta section
        content_parts.append(_build_discovery_section(disc_delta))

        # Reachability delta section
        content_parts.append(_build_reachability_section(reach_delta))

        content = "\n".join(content_parts)

        html = HTML_TEMPLATE.format(
            title=title,
            content=content,
            generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC"),
        )

        abs_path = os.path.abspath(output_path)
        ensure_directory(os.path.dirname(abs_path))
        with open(abs_path, "w", encoding="utf-8") as fh:
            fh.write(html)

        logger.info("HTML diff report written: %s", abs_path)
        return abs_path

    except Exception as exc:
        logger.error("Failed to generate diff report: %s", exc)
        raise


def generate_single_run_report(run_data: Dict[str, Any], output_path: str) -> str:
    """Generate an HTML report from a single run.json.

    Args:
        run_data: Parsed run.json structure.
        output_path: Path for the output HTML file.

    Returns:
        Absolute path of the generated HTML file.
    """
    logger.info("Generating single-run HTML report: %s", output_path)

    try:
        label = run_data.get("label", "Unknown Run")
        discovery = run_data.get("discovery", {})
        reachability = run_data.get("reachability", {})

        content_parts = []

        # Header
        content_parts.append(f"""
    <div class="header">
        <h1>HomeShield Run Report</h1>
        <div class="subtitle">Run: {label}</div>
        <div class="subtitle">Vantage: {run_data.get('vantage', 'N/A')} | Interface: {run_data.get('host', {}).get('interface', 'N/A')}</div>
        <div class="subtitle">Timestamp: {run_data.get('timestamp_utc', 'N/A')}</div>
    </div>""")

        # Discovery section
        mdns = discovery.get("mdns", {})
        ssdp = discovery.get("ssdp", {})
        mdns_ips = mdns.get("unique_responders", [])
        ssdp_ips = ssdp.get("unique_responders", [])

        content_parts.append(f"""
    <div class="section">
        <h2>Discovery Results</h2>
        <p>mDNS unique responders: <strong>{len(mdns_ips)}</strong> | SSDP unique responders: <strong>{len(ssdp_ips)}</strong></p>
        <table>
            <thead><tr><th>Protocol</th><th>Responder IP</th></tr></thead>
            <tbody>""")

        if not mdns_ips and not ssdp_ips:
            content_parts.append('            <tr><td colspan="2" class="empty">No responders discovered</td></tr>')
        else:
            for ip in mdns_ips:
                content_parts.append(f'            <tr><td>mDNS</td><td>{ip}</td></tr>')
            for ip in ssdp_ips:
                content_parts.append(f'            <tr><td>SSDP</td><td>{ip}</td></tr>')

        content_parts.append("        </tbody></table>\n    </div>")

        # Reachability section
        results = reachability.get("results", [])
        content_parts.append(f"""
    <div class="section">
        <h2>Reachability Results</h2>
        <p>Ports tested: {', '.join(str(p) for p in reachability.get('ports_tested', []))}</p>
        <table>
            <thead><tr><th>IP Address</th><th>Port</th><th>State</th><th>RTT (ms)</th></tr></thead>
            <tbody>""")

        if not results:
            content_parts.append('            <tr><td colspan="4" class="empty">No reachability results</td></tr>')
        else:
            for r in results:
                state_class = r["state"].lower()
                rtt = f"{r['rtt_ms']:.2f}" if r.get("rtt_ms") is not None else "—"
                content_parts.append(
                    f'            <tr><td>{r["dst_ip"]}</td><td>{r["port"]}</td>'
                    f'<td><span class="tag {state_class}">{r["state"]}</span></td>'
                    f'<td>{rtt}</td></tr>'
                )

        content_parts.append("        </tbody></table>\n    </div>")

        content = "\n".join(content_parts)

        html = HTML_TEMPLATE.format(
            title=label,
            content=content,
            generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC"),
        )

        abs_path = os.path.abspath(output_path)
        ensure_directory(os.path.dirname(abs_path))
        with open(abs_path, "w", encoding="utf-8") as fh:
            fh.write(html)

        logger.info("HTML single-run report written: %s", abs_path)
        return abs_path

    except Exception as exc:
        logger.error("Failed to generate single-run report: %s", exc)
        raise


def _build_discovery_section(disc_delta: Dict[str, Any]) -> str:
    """Build HTML section for discovery delta."""
    mdns = disc_delta.get("mdns", {})
    ssdp = disc_delta.get("ssdp", {})

    rows = []
    for ip in mdns.get("removed", []):
        rows.append(f'            <tr><td>mDNS</td><td>{ip}</td><td><span class="tag removed">REMOVED</span></td></tr>')
    for ip in mdns.get("added", []):
        rows.append(f'            <tr><td>mDNS</td><td>{ip}</td><td><span class="tag added">ADDED</span></td></tr>')
    for ip in ssdp.get("removed", []):
        rows.append(f'            <tr><td>SSDP</td><td>{ip}</td><td><span class="tag removed">REMOVED</span></td></tr>')
    for ip in ssdp.get("added", []):
        rows.append(f'            <tr><td>SSDP</td><td>{ip}</td><td><span class="tag added">ADDED</span></td></tr>')

    row_content = "\n".join(rows) if rows else '            <tr><td colspan="3" class="empty">No discovery changes</td></tr>'

    return f"""
    <div class="section">
        <h2>Discovery Changes</h2>
        <p>mDNS: {mdns.get('before_count', 0)} → {mdns.get('after_count', 0)} responders |
           SSDP: {ssdp.get('before_count', 0)} → {ssdp.get('after_count', 0)} responders</p>
        <table>
            <thead><tr><th>Protocol</th><th>IP Address</th><th>Status</th></tr></thead>
            <tbody>
{row_content}
            </tbody>
        </table>
    </div>"""


def _build_reachability_section(reach_delta: Dict[str, Any]) -> str:
    """Build HTML section for reachability delta."""
    rows = []
    for entry in reach_delta.get("removed", []):
        rows.append(
            f'            <tr><td>{entry["dst_ip"]}</td><td>{entry["port"]}</td>'
            f'<td><span class="tag removed">CLOSED (was OPEN)</span></td></tr>'
        )
    for entry in reach_delta.get("added", []):
        rows.append(
            f'            <tr><td>{entry["dst_ip"]}</td><td>{entry["port"]}</td>'
            f'<td><span class="tag added">OPEN (new)</span></td></tr>'
        )

    row_content = "\n".join(rows) if rows else '            <tr><td colspan="3" class="empty">No reachability changes</td></tr>'

    return f"""
    <div class="section">
        <h2>Reachability Changes</h2>
        <p>OPEN ports: {reach_delta.get('before_open_count', 0)} → {reach_delta.get('after_open_count', 0)}</p>
        <table>
            <thead><tr><th>IP Address</th><th>Port</th><th>Status</th></tr></thead>
            <tbody>
{row_content}
            </tbody>
        </table>
    </div>"""
